services:
  database:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Pichincha1
      - MYSQL_DATABASE=db_account_movements
    restart: always
    volumes:
      - /data:/var/lib/mysql

  client-person-service:
    build:
      context: ./client-person-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/db_account_movements
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pichincha1
    ports:
      - "8080:8080"
    depends_on:
      - database

  account_transaction_service:
    build:
      context: ./account-transactions-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/db_account_movements
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pichincha1
    ports:
      - "8081:8081"
    depends_on:
      - database

